name: Keep Render Alive

on:
  schedule:
    - cron: "*/5 * * * *"   # chạy mỗi 5 phút
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render
        run: |
          curl -s https://desktop-app1.onrender.com >/dev/null
